name: Build qubitcoin-miner for Windows x86_64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Install MSYS2 and dependencies
      run: |
        # Download and install MSYS2
        Invoke-WebRequest -Uri "https://repo.msys2.org/distrib/x86_64/msys2-x86_64-latest.exe" -OutFile msys2-installer.exe
        Start-Process -FilePath .\msys2-installer.exe -ArgumentList "/S /D=C:\msys64" -NoNewWindow -Wait
        
        # Update packages and install dependencies
        C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu"  # Core update (may need to be run twice)
        C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu"  # Second update if needed
        C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-curl mingw-w64-x86_64-gmp make"

    - name: Add MinGW to PATH
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

    - name: Configure build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: qubitcoin-miner
        path: build/qubitcoin-miner.exe
