name: Build qubitcoin-miner for Windows x86_64

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MSYS2
      run: |
        # Скачать и установить MSYS2
        Invoke-WebRequest -Uri https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20210725.exe -OutFile msys2-installer.exe
        Start-Process -FilePath .\msys2-installer.exe -ArgumentList "/S" -NoNewWindow -Wait
        # Обновить пакеты
        & C:\msys64\usr\bin\bash.exe -c "pacman -Sy --noconfirm base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-curl mingw-w64-x86_64-gmp"

    - name: Setup environment variables
      run: |
        echo "GCC_PATH=C:/msys64/mingw64/bin" >> $GITHUB_ENV
        echo "PATH=C:/msys64/mingw64/bin;${{ env.PATH }}" >> $GITHUB_ENV

    - name: Download qubitcoin-miner source
      run: |
        # В этом случае репозиторий уже есть, так что пропускаем
        # Или можно обновить
        git pull origin main

    - name: Prepare dependencies
      run: |
        # В этом проекте, скорее всего, есть CMake или Makefile
        # Проверим, что есть
        ls

    - name: Build qubitcoin-miner
      run: |
        # Предположим, что есть Makefile или CMake
        # Для Windows обычно используют CMake
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: qubitcoin-miner
        path: build/qubitcoin-miner.exe
